name: CI

env:
  CI: true

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  ci:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: cicdxl/action-es-package-ci@v0.2.0
        with:
          node-version: ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [16, 18]
