name: Publish

env:
  CI: true

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: esxl/action-package-build@v0.1.0
        with:
          node-version-file: .nvmrc

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
